apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      containers:
      - name: synergychat-api
        image: bootdotdev/synergychat-api:latest
        envFrom:                        # Loads ALL variables from the ConfigMap
          - configMapRef:
              name: synergychat-api-configmap
        volumeMounts:                   # Mounts the "hard drive" into the container
          - name: synergychat-api-volume
            mountPath: /persist
      volumes:                          # Defines the "hard drive" using the PVC ticket
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc