apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: crawler
spec:
  selector:
    app: synergychat-crawler  # Targets your crawler pods
  ports:
  - protocol: TCP
    port: 80         # Other pods (like API) call this port
    targetPort: 8080 # The container listens on this port

