apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: testcpu-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synergychat-testcpu  # <--- Points to your deployment
  minReplicas: 1
  maxReplicas: 1               # <--- The hard limit
  targetCPUUtilizationPercentage: 50
