apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: synergychat-web  # This connects the Service to your Web pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

