apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synergychat-web   # <--- Target the Web App
  minReplicas: 1            # <--- The Floor
  maxReplicas: 4            # <--- The Ceiling
  targetCPUUtilizationPercentage: 50
